### ISSUE TITLE
tank war drawing! faltou adicionar o link para o concept doc na página principal do repositório. 

### ISSUE THREAD

**Issue by ferkrum** [ferkrum/platAlt2020.1#11]

**Comment by GerritWerk** [comment]
sor na primeira pagina do git onde vc clica para ir na wiki tem o concept
doc q ja vai direto se tem q colocar la tbm vou fazer isso


Em qua., 1 de jul. de 2020 às 17:36, Fernando Krum <notifications@github.com>
escreveu:
